//
//  Slope_15_8.swift
//  YAEngine
//

import Foundation

/// Bitmap data for slope.
let slope15And8Bitmap: [TiledPoint] = [TiledPoint(x: 0, y: 0),
                                       TiledPoint(x: 1, y: 0),
                                       TiledPoint(x: 2, y: 0),
                                       TiledPoint(x: 3, y: 0),
                                       TiledPoint(x: 4, y: 0),
                                       TiledPoint(x: 5, y: 0),
                                       TiledPoint(x: 6, y: 0),
                                       TiledPoint(x: 7, y: 0),
                                       TiledPoint(x: 8, y: 0),
                                       TiledPoint(x: 9, y: 0),
                                       TiledPoint(x: 10, y: 0),
                                       TiledPoint(x: 11, y: 0),
                                       TiledPoint(x: 12, y: 0),
                                       TiledPoint(x: 13, y: 0),
                                       TiledPoint(x: 14, y: 0),
                                       TiledPoint(x: 15, y: 0),
                                       TiledPoint(x: 2, y: 1),
                                       TiledPoint(x: 3, y: 1),
                                       TiledPoint(x: 4, y: 1),
                                       TiledPoint(x: 5, y: 1),
                                       TiledPoint(x: 6, y: 1),
                                       TiledPoint(x: 7, y: 1),
                                       TiledPoint(x: 8, y: 1),
                                       TiledPoint(x: 9, y: 1),
                                       TiledPoint(x: 10, y: 1),
                                       TiledPoint(x: 11, y: 1),
                                       TiledPoint(x: 12, y: 1),
                                       TiledPoint(x: 13, y: 1),
                                       TiledPoint(x: 14, y: 1),
                                       TiledPoint(x: 15, y: 1),
                                       TiledPoint(x: 4, y: 2),
                                       TiledPoint(x: 5, y: 2),
                                       TiledPoint(x: 6, y: 2),
                                       TiledPoint(x: 7, y: 2),
                                       TiledPoint(x: 8, y: 2),
                                       TiledPoint(x: 9, y: 2),
                                       TiledPoint(x: 10, y: 2),
                                       TiledPoint(x: 11, y: 2),
                                       TiledPoint(x: 12, y: 2),
                                       TiledPoint(x: 13, y: 2),
                                       TiledPoint(x: 14, y: 2),
                                       TiledPoint(x: 15, y: 2),
                                       TiledPoint(x: 6, y: 3),
                                       TiledPoint(x: 7, y: 3),
                                       TiledPoint(x: 8, y: 3),
                                       TiledPoint(x: 9, y: 3),
                                       TiledPoint(x: 10, y: 3),
                                       TiledPoint(x: 11, y: 3),
                                       TiledPoint(x: 12, y: 3),
                                       TiledPoint(x: 13, y: 3),
                                       TiledPoint(x: 14, y: 3),
                                       TiledPoint(x: 15, y: 3),
                                       TiledPoint(x: 8, y: 4),
                                       TiledPoint(x: 9, y: 4),
                                       TiledPoint(x: 10, y: 4),
                                       TiledPoint(x: 11, y: 4),
                                       TiledPoint(x: 12, y: 4),
                                       TiledPoint(x: 13, y: 4),
                                       TiledPoint(x: 14, y: 4),
                                       TiledPoint(x: 15, y: 4),
                                       TiledPoint(x: 10, y: 5),
                                       TiledPoint(x: 11, y: 5),
                                       TiledPoint(x: 12, y: 5),
                                       TiledPoint(x: 13, y: 5),
                                       TiledPoint(x: 14, y: 5),
                                       TiledPoint(x: 15, y: 5),
                                       TiledPoint(x: 12, y: 6),
                                       TiledPoint(x: 13, y: 6),
                                       TiledPoint(x: 14, y: 6),
                                       TiledPoint(x: 15, y: 6),
                                       TiledPoint(x: 14, y: 7),
                                       TiledPoint(x: 15, y: 7)]
